update

diff --git a/ecommerce-react-python/Jenkinsfile b/ecommerce-react-python/Jenkinsfile
--- a/ecommerce-react-python/Jenkinsfile
+++ b/ecommerce-react-python/Jenkinsfile
@@ -1,13 +1,74 @@
 pipeline{
     agent { label 'electronix'}
 
+    environment{
+        S3_BUCKET='electronix-production-01'
+        CLOUDFRONT_ID='E1YW0HS96YMVZM'
+        AWS_REGION='us-east-1'
+    }
+
     stages{
-        stage("I am from elecronix"){
-            steps {echo "Hello from Elecronix Brand Delhi"}
+        stage("Frontend Deployment"){
+            when{
+                changeset "frontend/**"
+            }
+
+            stages{
+                stage('Install Dependencies'){
+                    steps{
+                        dir('frontend'){
+                            sh '''
+                            npm install
+                            '''
+                        }
+                    }
+                }
+
+                stage("Run Tests"){
+                    steps{
+                        dir('frontend'){
+                            sh 'npm test -- --watchAll=false || echo "No Test Configured.."'
+                        }
+                    }
+                }
+
+                stage("Build"){
+                    steps{
+                        dir('frontend'){
+                            sh 'npm run build'
+                        }
+                    }
+                }
+
+                stage('Deploy S3'){
+                    steps{
+                        dir('frontend'){
+                            sh '''
+                            aws s3 sync dist/ s3://${S3_BUCKET} --delete --region ${AWS_REGION}
+                            '''
+                        }
+                    }
+                }
+
+                
+                stage('Invalidation Cloudfront Cache'){
+                    steps{
+                        sh '''
+                        aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
+                        '''
+                    }
+                }
+            }
+        }
+    }
+
+    post{
+        success{
+            echo 'Frontent Deployment Successfull ✅'
         }
 
-    stage("I am from elecronix Setup"){
-            steps {echo "Elecronix Setup is Working "}
+        failure {
+           echo 'Frontent Deployment Failed ❌'
         }
-    }    
+    }
 }
