Refactor Jenkinsfile for better readability

diff --git a/ecommerce-react-python/Jenkinsfile b/ecommerce-react-python/Jenkinsfile
--- a/ecommerce-react-python/Jenkinsfile
+++ b/ecommerce-react-python/Jenkinsfile
@@ -1,60 +1,66 @@
-pipeline{
-    agent { label 'electronix'}
-
-    environment{
-        S3_BUCKET='electronix-production-01'
-        CLOUDFRONT_ID='E1YW0HS96YMVZM'
-        AWS_REGION='us-east-1'
+pipeline {
+    agent { 
+        label 'electronix' 
     }
 
-    stages{
-        stage("Frontend Deployment"){
-            when{
-                changeset "frontend/**"
-            }
+    environment {
+        S3_BUCKET = 'electronix-production-01'
+        CLOUDFRONT_ID = 'E1YW0HS96YMVZM'
+        AWS_REGION = 'us-east-1'
+    }
 
-            stages{
-                stage('Install Dependencies'){
-                    steps{
-                        dir('frontend'){
+    stages {
+
+        stage('Frontend Deployment') {
+
+            stages {
+
+                stage('Install Dependencies') {
+                    steps {
+                        dir('frontend') {
                             sh '''
-                            npm install
+                                npm install
                             '''
                         }
                     }
                 }
 
-                stage("Run Tests"){
-                    steps{
-                        dir('frontend'){
-                            sh 'npm test -- --watchAll=false || echo "No Test Configured.."'
-                        }
-                    }
-                }
-
-                stage("Build"){
-                    steps{
-                        dir('frontend'){
-                            sh 'npm run build'
-                        }
-                    }
-                }
-
-                stage('Deploy S3'){
-                    steps{
-                        dir('frontend'){
+                stage('Run Tests') {
+                    steps {
+                        dir('frontend') {
                             sh '''
-                            aws s3 sync dist/ s3://${S3_BUCKET} --delete --region ${AWS_REGION}
+                                npm test -- --watchAll=false || echo "No Test Configured."
                             '''
                         }
                     }
                 }
 
-                
-                stage('Invalidation Cloudfront Cache'){
-                    steps{
+                stage('Build') {
+                    steps {
+                        dir('frontend') {
+                            sh '''
+                                npm run build
+                            '''
+                        }
+                    }
+                }
+
+                stage('Deploy S3') {
+                    steps {
+                        dir('frontend') {
+                            sh '''
+                                aws s3 sync dist/ s3://${S3_BUCKET} --delete --region ${AWS_REGION}
+                            '''
+                        }
+                    }
+                }
+
+                stage('Invalidation CloudFront Cache') {
+                    steps {
                         sh '''
-                        aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
+                            aws cloudfront create-invalidation \
+                            --distribution-id ${CLOUDFRONT_ID} \
+                            --paths "/*"
                         '''
                     }
                 }
@@ -62,13 +68,13 @@ pipeline{
         }
     }
 
-    post{
-        success{
-            echo 'Frontent Deployment Successfull ✅'
+    post {
+        success {
+            echo 'Frontend Deployment Successful ✅'
         }
 
         failure {
-           echo 'Frontent Deployment Failed ❌'
+            echo 'Frontend Deployment Failed ❌'
         }
     }
 }
